language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
script: yarn build
addons:
  apt:
    update: false
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  target-branch: master
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
branch: source